### PR TITLE
Add the WayFinder Diagram

### PR DESCRIPTION
**Pull request by ThunderSon**
Add the WayFinder Diagram to the main page of the project.

@kingthorin when you have the time, please recommend if we should maybe inject it as an image, instead of inline HTML.

### CODE REVIEW

**Comment by kingthorin** [comment]
Well GitHub doesn't render it: https://github.com/OWASP/www-project-integration-standards/blob/dcdb050c42bc9864fd4d24a46178baee103ee983/index.md
image

It's probably more maintainable as an image.

**Comment by kingthorin** [comment]
So GitHub doesn't like it but it seems to deploy properly via gh-pages, plus I like the interactivity of it. So go for it!

**Comment by ThunderSon** [comment]
The issue is that Github Markdown Flavor doesn't render scripts. It reads them as text. On the other hand, Jekyll just serves what we need on gh-pages :)

**Comment by ThunderSon** [comment]
This works over 1920x1080 screens. We'll need to look into limiting the size of the diagram into the container it's in.

**Review by kingthorin — APPROVED** [review]
LGTM! :rocket:

**Comment by ThunderSon** [comment]
@robvanderveer @northdpole You can see the diagram on the project page.

**Pull request merged**
