### PR TITLE
links_in_sdlc_pic

### PR DESCRIPTION
**Pull request by northdpole**
added links to the sdlc diagram

### CODE REVIEW

**Comment by robvanderveer** [comment]
I like it and have a couple of remarks about form structure and content.

1. About the form:
Disadvantage:  My suggestion was to use a table so that the visualisation is more elegant/simple, allowing it to be more responsive (tablet, phone and especially powerpoint: a slide that shows the structure of OWASP). The current diagram is too complex for a slide. Another disadvantage of this form is that it’s hard to build it dynamically - which will be necessary in the future when we add more projects - also outside of OWASP.
Advantage: The diagram provides more opportunity for showing relations, which is really helpful.
I am in doubt whether we should  sacrifice simplicity for  expressiveness and wondering if a table would be better.
Let’s discuss.

2. About styling: what are the options to spice it up a little bit, for example to use blocks with fill colors and no borders, just to give it a more sophisticated look?

3. It needs a name/identity branding, so people can refer to it. Something that has a ring to it. For this, we have the opportunity to draw attention to our project and possibly to CRE at the same time. 
Let’s call it ‘Wayfinder’. And we can use the same term to refer to CRE.
I suggest to add a title IN the diagram (in the rectangle): “Application security wayfinder”
With subtitle “Highlighted OWASP tools, standards and guidelines, brought to you by the Integration standards project”.
When we launch this, we need a twitter/linkedin campaign. Who can we co-ordinate this with at OWASP?

Structure: 
4.We need a block where we can link SAMM to. Linking SAMM to ‘Requirements’ is not doing it justice and confusing. Let’s rename Culture building to “Mature process/organisation” and link the champion playbook, SAMM, Pipeline tools and Tool Benchmark. Remove SAMM from ‘Requirements’.
5.SAMM needs to be seen as OWASP’s view on the SDLC, so it would be more consistent and clear to the reader if we would use the SAMM as structure. How much are we stuck on this structure? On what standard is it based?
6.I suggest to drop ‘Policy gap evolution’. The purpose of the diagram is to order OWASP standards, but the standards this block links to already have been mentioned / are duplicates.

Content:
7.How about adding to Training/education: Webgoat, pyGoat, Snakes and ladders?
8.SKF is flagship and can be added to “Requirements” Also add securityRAT there??
9.Add Cornucopia to Design?
10.What is “Threat modeling talks”?
11. Where do you want to place Modsecurity?
12. OWTF to  testing guides
13. Where Code pulse?
14. CSRFguard is flagship. Add it to Secure libraries?
15.Add mobile top 10 to Training? It’s flagship
16.How about lab projects “top 10 privacy” and “API security?”?

Aligning it more with SAMM:
17. Rename Testing to Verification
18. Rename Coding to Implementation

**Comment by northdpole** [comment]
> I like it and have a couple of remarks about form structure and content.
> 
>     1. About the form:
>        Disadvantage:  My suggestion was to use a table so that the visualisation is more elegant/simple, allowing it to be more responsive (tablet, phone and especially powerpoint: a slide that shows the structure of OWASP). The current diagram is too complex for a slide. Another disadvantage of this form is that it’s hard to build it dynamically - which will be necessary in the future when we add more projects - also outside of OWASP.
>        Advantage: The diagram provides more opportunity for showing relations, which is really helpful.
>        I am in doubt whether we should  sacrifice simplicity for  expressiveness and wondering if a table would be better.
>        Let’s discuss.
> 
I agree with the table, but a table isn't as visually simple to look at, I think we can have both, this diagram can be auto-generated usign something like graphviz and a python script that parses CRE docs, table is just markdown, which can also be generated by parsing CRE docs.

>     2. About styling: what are the options to spice it up a little bit, for example to use blocks with fill colors and no borders, just to give it a more sophisticated look?
> 
something like this? https://drive.google.com/file/d/1ouMMPChLAp7gGBDJhfDvmk5nV4HkdaAT/view?usp=sharing

>     3. It needs a name/identity branding, so people can refer to it. Something that has a ring to it. For this, we have the opportunity to draw attention to our project and possibly to CRE at the same time.
>        Let’s call it ‘Wayfinder’. And we can use the same term to refer to CRE.
>        I suggest to add a title IN the diagram (in the rectangle): “Application security wayfinder”
>        With subtitle “Highlighted OWASP tools, standards and guidelines, brought to you by the Integration standards project”.
>        When we launch this, we need a twitter/linkedin campaign. Who can we co-ordinate this with at OWASP?
> 
We can ask people to retweet and share the original message, I don't think there's an official owasp marketing machine :) 
> 
> Structure:
> 4.We need a block where we can link SAMM to. Linking SAMM to ‘Requirements’ is not doing it justice and confusing. Let’s rename Culture building to “Mature process/organisation” and link the champion playbook, SAMM, Pipeline tools and Tool Benchmark. Remove SAMM from ‘Requirements’.

I'm not convinced about removing SAMM from Requirements, I have a few examples where people used SAMM-inspired abuse stories for requirement gathering. The thing with SAMM is that it is present kind of everywhere, what if we link to it in multiple places? (requriements, process maturing, policy gap evaluation)?

> 5.SAMM needs to be seen as OWASP’s view on the SDLC, so it would be more consistent and clear to the reader if we would use the SAMM as structure. How much are we stuck on this structure? On what standard is it based?
This structure follows SAMM pretty closely, the original diagram was made to compliment the owasp in the sdlc writeup which is pretty much SAMM with extra links to other projects.

Would you prefer to be closer to SAMM terminology on the green boxes? but then SAMM is missing a few steps, like metrics, gap evaluation, training, what do we do with these?

> 6.I suggest to drop ‘Policy gap evolution’. The purpose of the diagram is to order OWASP standards, but the standards this block links to already have been mentioned / are duplicates.
> 

Good point, the purpose of this is to capture a step for "retrospection and improvement" similar to what agile teams do with sprint planning and sprint retro.
SAMM and (M)ASVS discuss different levels of maturity for each step, how can we reflect that:
"once every N SDLC iterations, take some time to reflect on your metrics and plan how you can improve your process and reach a higher maturity level"?

> Content:
> 7.How about adding to Training/education: Webgoat, pyGoat, Snakes and ladders?
done
> 8.SKF is flagship and can be added to “Requirements” Also add securityRAT there??
done
> 9.Add Cornucopia to Design?
done
> 10.What is “Threat modeling talks”?
It's conference talks about threat modeling delivered in owasp cali, they're an educational source, how can we express this?
also having it there is a nice hint that owasp is not only tools and guides but also a decent ammount of videos material

> 11. Where do you want to place Modsecurity?
operations i guess, added a new step
> 12. OWTF to testing guides
done
> 13. Where Code pulse?
added
> 14. CSRFguard is flagship. Add it to Secure libraries?
done
> 15.Add mobile top 10 to Training? It’s flagship
done
> 16.How about lab projects “top 10 privacy” and “API security?”?
> 
API Top 10 is in "education" (added by you/Elie?)
added the privacy bit
full disclosure & slight rant: i'm not a big fan of a top 10 list for anything other than marketing material, it tends to draw attention away from what's important. not sure if mentioning various top 10 lists helps get our point across.

> Aligning it more with SAMM:
> 17. Rename Testing to Verification
done
> 18. Rename Coding to Implementation
done


when we have a slightly more final form i can produce anyother HTML document and updat this pull request :)

**Comment by robvanderveer** [comment]
-Let’s indeed consider both: table and diagram, and see what works best. 

-Styling: yes, solid shapes help  and perhaps with more contemporary colors such as the white on blue as the top bar of owasp.org for the rectangles and the black on blue-grey as the side bar for the circles.

-Yes, SAMM belongs to every element of the process, but it describes the process in a meta way, on the governance level not how to. For example it does not describe how you test. This is why I believe it deserves a special place, connected to an element we all ‘Organisation’.

-It’s not a problem that there is a mismatch between our process elements and those of SAMM if it helps to better organise the projects. Terminology alignment is the least we can do.

-You made me see the importance of mentioning process improvement. I think the ‘Organisation’ concept can be renamed to ‘Process improvement’ and link to SAMM, the playbook and also the process sections of ASVS and MASVS because you are right: these deal about process maturity as well.

-I think indeed that Top 10 was added to the education part by Elie. It’s a good decision NOT to put it under verification because I totally agree with your ‘rant’. Still, without the top 10, many people will not take our overview serious, so I think putting it under Education is fine.

**Comment by ThunderSon** [comment]
@northdpole When you're done from your side, let me know so I can go over everything.

I added the rest of the projects because the more projects you mention, the better. People look at Top 10, and then they'll say oh we're looking for mobile, whatever.
On the other side, no one would just ignore the diagram because it contains project names. They are like a cheat sheet, easy to digest and quick to reference and use. It better contain enough.

For the design stuff, it's nice and all, but let's keep that to professionals, unless you're consulting them, if you don't mind

**Comment by northdpole** [comment]
latest changes merged, let me know what else is needed :)

**Comment by ThunderSon** [comment]
It looks great. I'd say that the operation stage comes straight after Verification, as that's where most of the analytics comes from, and that's the SDLC flow.
For the requirements stage there's the SKF too. It's a knowledge base, so it could be more on the maturity level and processes. Otherwise it looks great.

**Comment by robvanderveer** [comment]
Wow, great improvement! We're very close to something we can release I think.
Points:
1. SKF is still missing. Perhaps there is a special reason for that? It belongs to Requirements.
2. Also change HTML title into "Application security wayfinder"?
3. Links in ASVS / SecurityRAT / MASVS are hard to click, probably because they are too close. You can hover the mouse over MASVS and still be taken to  Securityrat. The renderer is screwing up there. Perhaps this is fixed when SKF is added?
4. Add text to the arrow of 'operations': "Firewall rules" ?
5. A little bug: API top 10 takes you to the regular top 10
6. Make the "Integration standards project" a link?
7. A nice touch would be to link all github links to where the readme starts, for example for the cheat sheet series: https://github.com/OWASP/CheatSheetSeries#welcome-to-the-owasp-cheat-sheet-series. Otherwise, users first see just a file list.

**Review by ThunderSon — APPROVED** [review]

**Pull request merged**
